# Aulas de Análise de Dados — Pandas, NumPy e Prévia de Estatística  
**Data:** 25/08/2025

## Objetivos da aula (4h)
- Entender `Series` e `DataFrame` em **pandas**.
- Criar objetos a partir de listas, dicionários e escalares.
- Operações básicas com **NumPy** (vetores, matrizes, dimensões).
- Praticar com exercícios guiados e desafios.
- Olhar rápido para **média, mediana, moda** e **dispersão** (prévia de estatística).

---
**Dica didática:** Rode as células na ordem (Shift+Enter). Os blocos de _Exercícios_ vêm com sugestões e espaço para os(as) alunos(as) completarem.


In [1]:
# Instalação (se necessário) e imports
# Se estiver no Google Colab, descomente a linha abaixo:
# !pip install pandas numpy

import pandas as pd
import numpy as np
pd.__version__, np.__version__


('2.2.3', '2.2.5')

## 1) pandas.Series — Conceitos rápidos
Uma **Series** é um vetor unidimensional com **rótulos (índice)**. Pense em uma coluna de planilha com nomes nas linhas.


In [2]:
# 1. Criando uma Series a partir de uma lista
listaNotas = [10, 8, 5, 7]
serieNotas = pd.Series(listaNotas)

print("Lista Python:", listaNotas)
print("\nSeries pandas:")
print(serieNotas)


Lista Python: [10, 8, 5, 7]

Series pandas:
0    10
1     8
2     5
3     7
dtype: int64


In [3]:
# 2. Definindo um índice personalizado
indices = ['a', 'b', 'c', 'd']
serieNotas = pd.Series(listaNotas, index=indices)

print("Lista Python:", listaNotas)
print("\nSeries com índice personalizado:")
print(serieNotas)


Lista Python: [10, 8, 5, 7]

Series com índice personalizado:
a    10
b     8
c     5
d     7
dtype: int64


In [4]:
# 3. Criando Series a partir de um dicionário
dictAlunos = {
    "nome": "João",
    "nota": 10,
    "Matricula": 123123,
    "data": 20200503
}
SerieAlunos = pd.Series(dictAlunos)

print("Dicionário:", dictAlunos)
print("\nSeries criada de dicionário:")
print(SerieAlunos)


Dicionário: {'nome': 'João', 'nota': 10, 'Matricula': 123123, 'data': 20200503}

Series criada de dicionário:
nome             João
nota               10
Matricula      123123
data         20200503
dtype: object


In [5]:
# 4. Criando Series a partir de um valor escalar (repetido)
serieRepetido = pd.Series(10, index=[0, 1, 2, 3, 4, 5])
print(serieRepetido)


0    10
1    10
2    10
3    10
4    10
5    10
dtype: int64


In [6]:
# 5. Usando o parâmetro dtype e name
listaAlunos = ['Ana', 'Maria', 'João']
SerieAlunos = pd.Series(listaAlunos, dtype=str, name='ListaAlunos')
print("Lista bruta:", listaAlunos)
print("\nSeries tipada e nomeada:")
print(SerieAlunos)
print("\nAtributos úteis -> index, dtype, name:", SerieAlunos.index, SerieAlunos.dtype, SerieAlunos.name)


Lista bruta: ['Ana', 'Maria', 'João']

Series tipada e nomeada:
0      Ana
1    Maria
2     João
Name: ListaAlunos, dtype: object

Atributos úteis -> index, dtype, name: RangeIndex(start=0, stop=3, step=1) object ListaAlunos


### 🧪 Exercício rápido — Series
1. Crie uma `Series` com 4 cidades brasileiras e seus respectivos códigos DDD como índice.  
2. Renomeie a `Series` para `DDDs`.  
3. Selecione o DDD da segunda cidade usando **rótulo** e usando **posição**.


In [7]:
# ➜ Escreva seu código aqui
# Dica: pd.Series(valores, index=rotulos, name="DDDs")


## 2) pandas.DataFrame — Conceitos rápidos
Um **DataFrame** é uma tabela (linhas x colunas). É o tipo mais usado em dados tabulares.


In [8]:
# 1. Criando um DataFrame a partir de um dicionário de listas
dados = {
    "nomes": ['Ana', 'João', 'Maria'],
    "idades": [23, 35, 31],
    "notas": [8.5, 7, 9.2]
}
print("Dicionário de listas:", dados)

dataDados = pd.DataFrame(dados)
print("\nDataFrame:")
print(dataDados)


Dicionário de listas: {'nomes': ['Ana', 'João', 'Maria'], 'idades': [23, 35, 31], 'notas': [8.5, 7, 9.2]}

DataFrame:
   nomes  idades  notas
0    Ana      23    8.5
1   João      35    7.0
2  Maria      31    9.2


In [9]:
# 2. Definindo um índice personalizado
dataDados = pd.DataFrame(dados, index=['a', 'b', 'c'])
print(dataDados)


   nomes  idades  notas
a    Ana      23    8.5
b   João      35    7.0
c  Maria      31    9.2


In [10]:
# 3. Criando DataFrame a partir de uma lista de dicionários
dados = [
    {"nome": "Ana", "idade": 23},
    {"nome": "João", "idade": 35, "nota": 10},
    {"nome": "Maria", "nota": 9.2},
]
dados = pd.DataFrame(dados)
print(dados)


    nome  idade  nota
0    Ana   23.0   NaN
1   João   35.0  10.0
2  Maria    NaN   9.2


In [11]:
# 4. Criando um DataFrame a partir de uma única Series (coluna)
listaNumeros = [10, 20, 30]
print("Lista:", listaNumeros)
listaNumeros = pd.DataFrame(listaNumeros, columns=["valores"])
print(listaNumeros)


Lista: [10, 20, 30]
   valores
0       10
1       20
2       30


In [12]:
# Operações básicas úteis para aula
df = pd.DataFrame({
    "aluno": ["Ana", "João", "Maria", "Pedro"],
    "nota": [8.5, 7.0, 9.2, 6.8],
    "idade": [23, 35, 31, 29]
})
print(df)

print("\nEstatísticas descritivas rápidas:")
print(df.describe())

print("\nSelecionando colunas/linhas:")
print("Coluna nota:\n", df["nota"])
print("\nPrimeiras linhas:\n", df.head(2))
print("\nFiltro (nota >= 8):\n", df[df["nota"] >= 8])


   aluno  nota  idade
0    Ana   8.5     23
1   João   7.0     35
2  Maria   9.2     31
3  Pedro   6.8     29

Estatísticas descritivas rápidas:
           nota  idade
count  4.000000    4.0
mean   7.875000   29.5
std    1.164403    5.0
min    6.800000   23.0
25%    6.950000   27.5
50%    7.750000   30.0
75%    8.675000   32.0
max    9.200000   35.0

Selecionando colunas/linhas:
Coluna nota:
 0    8.5
1    7.0
2    9.2
3    6.8
Name: nota, dtype: float64

Primeiras linhas:
   aluno  nota  idade
0   Ana   8.5     23
1  João   7.0     35

Filtro (nota >= 8):
    aluno  nota  idade
0    Ana   8.5     23
2  Maria   9.2     31


### 🧪 Exercício — DataFrame
Crie um `DataFrame` com colunas **produto**, **preço**, **estoque** (3 a 5 linhas). Depois:
1. Adicione uma coluna `valor_total` = `preço` × `estoque`  
2. Filtre apenas os produtos com `estoque` > 10  
3. Mostre as estatísticas descritivas


In [13]:
# ➜ Escreva seu código aqui


## 3) NumPy — Vetores e Matrizes
**NumPy** é uma biblioteca para computação numérica eficiente. `ndarray` é a estrutura central.


In [14]:
lista1 = [1, 2, 3, 4, 5]
lista1Dobro = []

for numero in lista1:
    dobro = numero * 2
    lista1Dobro.append(dobro)

print("Dobro (Python puro):", lista1Dobro)

lista2 = np.array(lista1)
print("Array NumPy:", lista2)

lista2 = lista2 + 2
print("Array + 2:", lista2)


Dobro (Python puro): [2, 4, 6, 8, 10]
Array NumPy: [1 2 3 4 5]
Array + 2: [3 4 5 6 7]


In [15]:
# Matrizes e cubos (tensores)
mat1 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print("Lista aninhada:", mat1)

mat2 = np.array(mat1)
print("\nndarray:")
print(mat2)

vetor = [1, 2, 3, 4, 5]
mat1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
cubo = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

vetor = np.array(vetor)
mat1 = np.array(mat1)
cubo = np.array(cubo)

# Número de dimensões
print("ndim -> vetor, mat, cubo:", vetor.ndim, mat1.ndim, cubo.ndim)
print("shape ->", vetor.shape, mat1.shape, cubo.shape)
print("size  ->", vetor.size, mat1.size, cubo.size)


Lista aninhada: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

ndarray:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim -> vetor, mat, cubo: 1 2 3
shape -> (5,) (3, 3) (2, 2, 2)
size  -> 5 9 8


In [16]:
# Arrays especiais
matZero = np.zeros((3, 3))
print(matZero + 10)

matUm = np.ones((2, 2))
print(matUm)

matID = np.eye(3)  # matriz identidade
print(matID)


[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# Espaços e aleatoriedade
vetor1 = np.arange(0, 1.05, 0.05)
print(vetor1)

matAleatorio = np.random.rand(10, 10)
print(np.floor(matAleatorio * 101))  # inteiros de 0 a 100


[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95 1.  ]
[[ 31.  62.  61.  58.   7.  81.  53.  71.  55.  85.]
 [ 57.  81.  60. 100.  48.  55.  28.  48.  78.  13.]
 [ 71.  24.  48.  83.  56.  41.  12.  30.  14.  39.]
 [ 29.  72.  98.   3.  56.  51.  88.  81.  37.  84.]
 [ 73.  57.  35.  98.  42.  84.  10.  48.  30.   1.]
 [ 39.  75.  71.  68.  49.  18.   2.   6.  50.  82.]
 [ 62.  41.  19.  76.  21.  33.  82.  68.  19.  62.]
 [ 72.  21.  69.  53.  64.  17.  24.  70.  43.  20.]
 [  2.  70.  20.  75.  54.  75.  62.  63.  39.  23.]
 [ 58.  34.  78.   4.  79.  50.   5.  78.  86.  89.]]


### 🧪 Exercícios — NumPy
1. **Crie**:  
   - Um array 1D de 5 inteiros.  
   - Uma matriz 3x3 de números aleatórios **inteiros** entre 0 e 10 (inclusive).  
2. **Faça**:  
   - A soma de dois arrays.  
   - A multiplicação de um array por um número.  
   - O quadrado de todos os elementos de um array.  
3. **Mostre**:  
   - `ndim`, `shape`, `dtype`, `size` de um array 2D.


In [18]:
# ➜ Escreva seu código aqui
# Dica: np.random.randint(0, 11, size=(3,3))


## 4) Prévia de Estatística
Vamos aplicar **média, mediana, moda** e medir **dispersão** rapidamente.


In [19]:
from statistics import mode, multimode
import numpy as np
import pandas as pd

ex = pd.Series([8.5, 7.0, 9.2, 6.8, 8.5, 7.0, 8.5], name="notas")

print("Série de exemplo:")
print(ex.to_string(index=False))

print("\nMédia (np):", np.mean(ex))
print("Mediana (np):", np.median(ex))
try:
    print("Moda (statistics.mode):", mode(ex))
except:
    print("Moda não única, usando multimode:", multimode(ex))

print("\nVariância (pandas, populacional=False):", ex.var(ddof=1))
print("Desvio padrão (pandas, ddof=1):", ex.std(ddof=1))
print("Desvio médio absoluto:", ex.mad())
print("\nResumo describe():\n", ex.describe())


Série de exemplo:
8.5
7.0
9.2
6.8
8.5
7.0
8.5

Média (np): 7.928571428571429
Mediana (np): 8.5
Moda (statistics.mode): 8.5

Variância (pandas, populacional=False): 0.932380952380952
Desvio padrão (pandas, ddof=1): 0.9655987533033336


AttributeError: 'Series' object has no attribute 'mad'

## Encerramento & Próximos passos
- **Hoje**: fundamentos de `Series`, `DataFrame` e `NumPy` + estatística **descritiva** básica.  
- **Próxima aula**: medidas de **tendência central** vs **dispersão**, **correlação** e **amostragem** (com `pandas` e `scipy`).

### 🏠 Tarefa (opcional)
- Monte um `DataFrame` com notas de 10 alunos, calcule média/mediana/moda e desvio padrão por turma.  
- Gere um gráfico simples com `matplotlib` de distribuição de notas (histograma).

---
### Apêndice: Cheatsheet mini
- `pd.Series(data, index=..., dtype=..., name=...)`  
- `pd.DataFrame(dict|list, index=..., columns=...)`  
- Seleção: `df['col']`, `df.loc[rotulo]`, `df.iloc[pos]`  
- Estatísticas: `df.describe()`, `s.mean()`, `s.median()`, `s.mode()`  
- NumPy criação: `np.array`, `np.zeros`, `np.ones`, `np.eye`, `np.arange`, `np.random`  
- Propriedades: `ndim`, `shape`, `dtype`, `size`
